from enum import StrEnum


class OrganizationRole(StrEnum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    MANAGER = "MANAGER"
    SUPPORT_AGENT = "SUPPORT_AGENT"
    VIEWER = "VIEWER"


class MemberStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INVITED = "INVITED"
    SUSPENDED = "SUSPENDED"


class IntegrationProvider(StrEnum):
    URBANKART = "URBANKART"


class IntegrationStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    ERROR = "ERROR"


class ExternalApiStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class TicketStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_FOR_CUSTOMER = "WAITING_FOR_CUSTOMER"
    WAITING_FOR_INTERNAL_REVIEW = "WAITING_FOR_INTERNAL_REVIEW"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class TicketPriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class TicketCategory(StrEnum):
    ORDER_STATUS = "ORDER_STATUS"
    PAYMENT_ISSUE = "PAYMENT_ISSUE"
    REFUND_REQUEST = "REFUND_REQUEST"
    RETURN_REPLACEMENT = "RETURN_REPLACEMENT"
    PRODUCT_QUESTION = "PRODUCT_QUESTION"
    DELIVERY_ISSUE = "DELIVERY_ISSUE"
    ACCOUNT_ISSUE = "ACCOUNT_ISSUE"
    COMPLAINT = "COMPLAINT"
    LEGAL_RISK = "LEGAL_RISK"
    OTHER = "OTHER"


class TicketSource(StrEnum):
    SUPPORT_FORM = "SUPPORT_FORM"
    WEB_WIDGET = "WEB_WIDGET"
    EMAIL = "EMAIL"
    WHATSAPP = "WHATSAPP"
    API = "API"
    MANUAL = "MANUAL"


class TicketMessageSenderType(StrEnum):
    CUSTOMER = "CUSTOMER"
    AGENT = "AGENT"
    AI = "AI"
    SYSTEM = "SYSTEM"


class TicketTimelineEventType(StrEnum):
    TICKET_CREATED = "TICKET_CREATED"
    MESSAGE_ADDED = "MESSAGE_ADDED"
    INTERNAL_NOTE_ADDED = "INTERNAL_NOTE_ADDED"
    STATUS_CHANGED = "STATUS_CHANGED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    CATEGORY_CHANGED = "CATEGORY_CHANGED"
    ASSIGNEE_CHANGED = "ASSIGNEE_CHANGED"
    CUSTOMER_UPDATED = "CUSTOMER_UPDATED"
    LIFECYCLE_TRANSITION = "LIFECYCLE_TRANSITION"
    LIFECYCLE_TRANSITION_BLOCKED = "LIFECYCLE_TRANSITION_BLOCKED"
    AGENT_RUN_STARTED = "AGENT_RUN_STARTED"
    AGENT_RUN_COMPLETED = "AGENT_RUN_COMPLETED"
    AGENT_RUN_FAILED = "AGENT_RUN_FAILED"
    TOOL_EXECUTION_STARTED = "TOOL_EXECUTION_STARTED"
    TOOL_EXECUTION_COMPLETED = "TOOL_EXECUTION_COMPLETED"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    TOOL_EXECUTION_BLOCKED = "TOOL_EXECUTION_BLOCKED"
    APPROVAL_REQUEST_CREATED = "APPROVAL_REQUEST_CREATED"
    APPROVAL_REQUEST_APPROVED = "APPROVAL_REQUEST_APPROVED"
    APPROVAL_REQUEST_REJECTED = "APPROVAL_REQUEST_REJECTED"
    APPROVED_TOOL_EXECUTION_STARTED = "APPROVED_TOOL_EXECUTION_STARTED"
    APPROVED_TOOL_EXECUTION_COMPLETED = "APPROVED_TOOL_EXECUTION_COMPLETED"
    APPROVED_TOOL_EXECUTION_FAILED = "APPROVED_TOOL_EXECUTION_FAILED"
    REPLY_DRAFT_CREATED = "REPLY_DRAFT_CREATED"
    REPLY_DRAFT_UPDATED = "REPLY_DRAFT_UPDATED"
    REPLY_DRAFT_SUBMITTED_FOR_APPROVAL = "REPLY_DRAFT_SUBMITTED_FOR_APPROVAL"
    REPLY_DRAFT_APPROVED = "REPLY_DRAFT_APPROVED"
    REPLY_DRAFT_REJECTED = "REPLY_DRAFT_REJECTED"
    CUSTOMER_REPLY_SENT = "CUSTOMER_REPLY_SENT"
    SLA_NEAR_BREACH = "SLA_NEAR_BREACH"
    SLA_BREACHED = "SLA_BREACHED"


class TicketTransitionTrigger(StrEnum):
    AGENT_ACTION = "AGENT_ACTION"
    AI_ACTION = "AI_ACTION"
    CUSTOMER_REPLY = "CUSTOMER_REPLY"
    SYSTEM_POLICY = "SYSTEM_POLICY"
    APPROVAL_DECISION = "APPROVAL_DECISION"

class TicketSlaStatus(StrEnum):
    OK = "OK"
    NEAR_BREACH = "NEAR_BREACH"
    BREACHED = "BREACHED"
    
    
class KnowledgeDocumentType(StrEnum):
    POLICY = "POLICY"
    FAQ = "FAQ"
    SOP = "SOP"
    MACRO = "MACRO"
    PRODUCT_INFO = "PRODUCT_INFO"
    SHIPPING_POLICY = "SHIPPING_POLICY"
    REFUND_POLICY = "REFUND_POLICY"
    RETURN_POLICY = "RETURN_POLICY"
    OTHER = "OTHER"


class KnowledgeDocumentStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class KnowledgeIngestionStatus(StrEnum):
    PENDING = "PENDING"
    INGESTED = "INGESTED"
    FAILED = "FAILED"


class AgentRunStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AgentStepStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AgentDecision(StrEnum):
    AUTO_REPLY_DRAFT = "AUTO_REPLY_DRAFT"
    NEEDS_HUMAN_APPROVAL = "NEEDS_HUMAN_APPROVAL"
    ESCALATE_TO_MANAGER = "ESCALATE_TO_MANAGER"
    ASK_CUSTOMER_FOR_MORE_INFO = "ASK_CUSTOMER_FOR_MORE_INFO"
    NO_ACTION = "NO_ACTION"


class AgentRiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    
    
class ToolRiskLevel(StrEnum):
    READ_ONLY = "READ_ONLY"
    LOW_RISK_WRITE = "LOW_RISK_WRITE"
    HIGH_RISK_WRITE = "HIGH_RISK_WRITE"


class ToolExecutionStatus(StrEnum):
    STARTED = "STARTED"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    BLOCKED_APPROVAL_REQUIRED = "BLOCKED_APPROVAL_REQUIRED"
    SKIPPED = "SKIPPED"


class ToolApprovalStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED = "REQUIRED"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ToolName(StrEnum):
    URBANKART_GET_ORDER_CONTEXT = "urbankart_get_order_context"
    URBANKART_REQUEST_REFUND = "urbankart_request_refund"
    
class ApprovalRequestStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class ApprovalRequestType(StrEnum):
    TOOL_EXECUTION = "TOOL_EXECUTION"
    CUSTOMER_REPLY = "CUSTOMER_REPLY"
    TICKET_ESCALATION = "TICKET_ESCALATION"
    

class CustomerReplyDraftStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SENT = "SENT"
    CANCELLED = "CANCELLED"


class CustomerReplyDraftSource(StrEnum):
    AI = "AI"
    AGENT = "AGENT"
    TEMPLATE = "TEMPLATE"
    
    
class AuditAction(StrEnum):
    TICKET_CREATED = "TICKET_CREATED"
    TICKET_UPDATED = "TICKET_UPDATED"
    TICKET_MESSAGE_ADDED = "TICKET_MESSAGE_ADDED"
    TICKET_INTERNAL_NOTE_ADDED = "TICKET_INTERNAL_NOTE_ADDED"
    TICKET_STATUS_CHANGED = "TICKET_STATUS_CHANGED"

    AGENT_RUN_STARTED = "AGENT_RUN_STARTED"
    AGENT_RUN_COMPLETED = "AGENT_RUN_COMPLETED"
    AGENT_RUN_FAILED = "AGENT_RUN_FAILED"

    TOOL_EXECUTION_STARTED = "TOOL_EXECUTION_STARTED"
    TOOL_EXECUTION_BLOCKED = "TOOL_EXECUTION_BLOCKED"
    TOOL_EXECUTION_COMPLETED = "TOOL_EXECUTION_COMPLETED"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    APPROVED_TOOL_EXECUTION_STARTED = "APPROVED_TOOL_EXECUTION_STARTED"
    APPROVED_TOOL_EXECUTION_COMPLETED = "APPROVED_TOOL_EXECUTION_COMPLETED"
    APPROVED_TOOL_EXECUTION_FAILED = "APPROVED_TOOL_EXECUTION_FAILED"

    APPROVAL_REQUEST_CREATED = "APPROVAL_REQUEST_CREATED"
    APPROVAL_REQUEST_APPROVED = "APPROVAL_REQUEST_APPROVED"
    APPROVAL_REQUEST_REJECTED = "APPROVAL_REQUEST_REJECTED"

    REPLY_DRAFT_CREATED = "REPLY_DRAFT_CREATED"
    REPLY_DRAFT_UPDATED = "REPLY_DRAFT_UPDATED"
    REPLY_DRAFT_SUBMITTED_FOR_APPROVAL = "REPLY_DRAFT_SUBMITTED_FOR_APPROVAL"
    REPLY_DRAFT_APPROVED = "REPLY_DRAFT_APPROVED"
    REPLY_DRAFT_REJECTED = "REPLY_DRAFT_REJECTED"
    CUSTOMER_REPLY_SENT = "CUSTOMER_REPLY_SENT"

    SLA_NEAR_BREACH = "SLA_NEAR_BREACH"
    SLA_BREACHED = "SLA_BREACHED"

    ORGANIZATION_UPDATED = "ORGANIZATION_UPDATED"
    INTEGRATION_UPDATED = "INTEGRATION_UPDATED"


class AuditResourceType(StrEnum):
    TICKET = "TICKET"
    TICKET_MESSAGE = "TICKET_MESSAGE"
    TICKET_INTERNAL_NOTE = "TICKET_INTERNAL_NOTE"
    AGENT_RUN = "AGENT_RUN"
    TOOL_EXECUTION = "TOOL_EXECUTION"
    APPROVAL_REQUEST = "APPROVAL_REQUEST"
    REPLY_DRAFT = "REPLY_DRAFT"
    ORGANIZATION = "ORGANIZATION"
    INTEGRATION = "INTEGRATION"
    SLA = "SLA"